/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swing;

import dao.AdministratorDAO;
import dao.EducationDAO;
import dao.StudentDAO;
import dao.TeacherDAO;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import metier.AbstractUser;
import metier.Administrator;
import metier.Education;
import metier.School;
import metier.Student;
import metier.Teacher;
import utils.PasswordUtils;
import utils.UserType;

/**
 *
 * @author Madeleine
 */
public class AddUserUI extends javax.swing.JFrame {

    private School mySchool;
    /**
     * Creates new form AddUserUI
     */
    public AddUserUI() {
        initComponents();
    }
    
    public AddUserUI(School pSchool) {
        initComponents();
        // saving user schoolID
        // --------------------
        this.mySchool = pSchool;
        this.initComboBox();
    }
    
    /**
     * ==============
     * Init JComboBox
     * ==============
     */
    private void initComboBox() {
        Integer daysValue[] = new Integer[31];
        Integer monthValue[] = new Integer[12];
        Integer yearValue[] = new Integer[100];
        String  typeValue[] = new String[3];
        
        EducationDAO eduDAO = new EducationDAO();
        List    listEdu = eduDAO.selectAllBySchoolId(this.mySchool.getId()); //getting all education from a school
        DefaultComboBoxModel dcbmEdu = new DefaultComboBoxModel();
        
        // Education Value from School
        // ---------------------------
        for (Object o : listEdu) {
            Education myEdu = (Education) o;
            dcbmEdu.addElement(myEdu);
        }
        
        // Day in Month Value
        // ------------------
        for (int i = 0; i < daysValue.length; i++) {
            daysValue[i] = i+1;
        }
        
        // Month in Year Value
        // -------------------
        for (int i = 0; i < monthValue.length; i++) {
            monthValue[i] = i+1;
        }
        
        // Year Value (50 max)
        // -------------------
        for (int i = 0; i < yearValue.length; i++) {
            yearValue[i] = i+1914;
        }
        
        // User Type Value
        // ---------------
        for (int i = 0; i < typeValue.length; i++) {
            switch(i) {
                case 0:
                    typeValue[i] = "Eleve";
                    break;
                    
                case 1:
                    typeValue[i] = "Professeur";
                    break;
                    
                case 2:
                    typeValue[i] = "Admin";
                    break;
            }
        }
        
        DefaultComboBoxModel dcbmDay = new DefaultComboBoxModel(daysValue);
        DefaultComboBoxModel dcbmMonth = new DefaultComboBoxModel(monthValue);
        DefaultComboBoxModel dcbmYear = new DefaultComboBoxModel(yearValue);
        DefaultComboBoxModel dcbmType = new DefaultComboBoxModel(typeValue);
        this.combob_day.setModel(dcbmDay);
        this.combob_month.setModel(dcbmMonth);
        this.combob_year.setModel(dcbmYear);
        this.combob_type.setModel(dcbmType);
        this.combob_education.setModel(dcbmEdu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        lbl_winTitle = new javax.swing.JLabel();
        combob_type = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_lastName = new javax.swing.JTextField();
        tf_firstName = new javax.swing.JTextField();
        tf_mail = new javax.swing.JTextField();
        combob_day = new javax.swing.JComboBox();
        combob_month = new javax.swing.JComboBox();
        combob_year = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        tf_login = new javax.swing.JTextField();
        tf_passwd = new javax.swing.JPasswordField();
        bt_addUser = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        combob_education = new javax.swing.JComboBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_winTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbl_winTitle.setForeground(new java.awt.Color(0, 102, 204));
        lbl_winTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_winTitle.setText("Ajout d'utilisateur");

        combob_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Nom:");

        jLabel2.setText("Prénom:");

        jLabel3.setText("E-mail:");

        jLabel4.setText("Date de Naissance:");

        jLabel5.setText("Login:");

        combob_day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combob_month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combob_year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Mot de Passe:");

        bt_addUser.setText("Ajouter");
        bt_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addUserActionPerformed(evt);
            }
        });

        jLabel7.setText("Formation:");

        combob_education.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_winTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_addUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(combob_type, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combob_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combob_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combob_year, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_firstName)
                                    .addComponent(tf_mail)
                                    .addComponent(tf_login)
                                    .addComponent(tf_passwd)
                                    .addComponent(combob_education, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_lastName)))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_winTitle)
                .addGap(18, 18, 18)
                .addComponent(combob_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combob_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combob_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combob_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combob_education, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bt_addUser)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addUserActionPerformed
        // TODO add your handling code here:
        
         // getting data from form
        // ----------------------
        String          aLogin = this.tf_login.getText();
        String          cleanPwd = new String(this.tf_passwd.getPassword());
        String          cryptPwd = PasswordUtils.getMD5Str(cleanPwd); //crypt password using MD5
        String          strType = this.combob_type.getSelectedItem().toString();
        String          aFirstName = this.tf_firstName.getText();
        String          aLastName = this.tf_lastName.getText();
        String          aMail = this.tf_mail.getText();
        Calendar        myCal = Calendar.getInstance(); // set a calendar to init sql.Date
        myCal.set(Calendar.YEAR, ((Integer)combob_year.getSelectedItem()).intValue());
        myCal.set(Calendar.MONTH, ((Integer)combob_month.getSelectedItem()).intValue());
        myCal.set(Calendar.DAY_OF_MONTH, ((Integer)combob_day.getSelectedItem()).intValue());
        Date            aBirthDate = new Date(myCal.getTime().getTime());
        Education       anEdu = (Education)this.combob_education.getSelectedItem();
        AbstractUser    aUser = null;
        UserType        anUserType = null;
        
        System.out.println("type d'utilisateur: " + strType);
        System.out.println("login: " + aLogin);
        System.out.println("clean pass: " + cleanPwd);
        System.out.println("crypt pass: " + cryptPwd);
        System.out.println("mail: " + aMail);
        System.out.println("first name: " + aFirstName);
        System.out.println("last name: " + aLastName);
        System.out.println("date de naissance:" + aBirthDate);
        System.out.println("formation:" + anEdu);
        System.out.println("école:" + this.mySchool);

        // setting user type
        // -----------------
        if (strType.compareTo("Eleve") == 0) { // a student
            anUserType = UserType.STUDENT;
            aUser = new Student(aLogin, cryptPwd, aMail, aBirthDate, aFirstName, aLastName, 0, this.mySchool, anEdu);
            System.out.println(aUser);
            StudentDAO studentDAO = new StudentDAO();
            studentDAO.insert((Student)aUser);
        }
        else if (strType.compareTo("Professeur") == 0) { // a teacher
            anUserType = UserType.TEACHER;
            aUser = new Teacher(aLogin, cryptPwd, aMail, aBirthDate, aFirstName, aLastName, 0, this.mySchool, null);
            System.out.println(aUser);
            TeacherDAO teacherDAO = new TeacherDAO();
            teacherDAO.insert((Teacher)aUser);
        }
        else if (strType.compareTo("Administration") == 0) { // an admin user
            anUserType = UserType.ADMIN;
            aUser = new Administrator(aLogin, cryptPwd, aMail, aBirthDate, aFirstName, aLastName, 0, this.mySchool, null);
            System.out.println(aUser);
            AdministratorDAO adminDAO = new AdministratorDAO();
            adminDAO.insert((Administrator)aUser);
        }
        
        this.dispose();
    }//GEN-LAST:event_bt_addUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addUser;
    private javax.swing.JComboBox combob_day;
    private javax.swing.JComboBox combob_education;
    private javax.swing.JComboBox combob_month;
    private javax.swing.JComboBox combob_type;
    private javax.swing.JComboBox combob_year;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_winTitle;
    private javax.swing.JTextField tf_firstName;
    private javax.swing.JTextField tf_lastName;
    private javax.swing.JTextField tf_login;
    private javax.swing.JTextField tf_mail;
    private javax.swing.JPasswordField tf_passwd;
    // End of variables declaration//GEN-END:variables
}
